### ISSUE TITLE
Coverage html filename has too few identifiers

### ISSUE THREAD

**Issue by woook** [eastgenomics/athena#27]
The html file only appears to take up to the first underscore of the input filename. 
This may not be sufficient to unambiguously identify which sample the coverage report is for.

Please consider changing the logic here.
However, please also consider the effect of the lab changing their sample naming convention to use hyphens rather than underscores.

**Comment by jethror1** [comment]
Magical, I can transfer it myself

**Comment by woook** [comment]
I've got a feeling that underscore will end up being the separator so you may have been rather prescient. 
Will confirm

**Comment by jethror1** [comment]
did you get to a decision on this?

**Comment by jethror1** [comment]
Closing this as everything unique is separated by `-`, and `--sample-name` is used in report workflow anyway to pass in sample ID for naming
