### ISSUE TITLE
Include absolute coverage values for genes in suboptimal coverage list of html report

### ISSUE THREAD

**Issue by mattgarner** [eastgenomics/athena#28]
e.g.
```
Genes with coverage at 20x less than 90%: ARPC1B (NM_005720.3); FYB1 (NM_001465.4); MPIG6B (NM_025260.3); SLFN14 (NM_001129820.1); TPM4 (NM_001145160.1).
```
would become
```
Genes with coverage at 20x less than 90%: ARPC1B (NM_005720.3) 89.9%; FYB1 (NM_001465.4) 50.1%; MPIG6B (NM_025260.3) 10.6%; SLFN14 (NM_001129820.1) 0.1%; TPM4 (NM_001145160.1) 0.0%.
```

(There might be a better way to present this than the format suggested above)

**Comment by jethror1** [comment]
For now they get generated like this, not sure if it would be better to have them in some kind of grid. Does this affect scientists copy pasting this text (i.e. if I put a load of new lines etc.)

```Genes with coverage at 20x less than 90%: ACD (NM_001082486.1) 0.0%; ARPC1B (NM_005720.3) 0.0%; ATP6AP1 (NM_001183.5) 0.0%; BACH2 (NM_021813.3) 0.0%; C4A (NM_007293.2) 32.87%; C4B (NM_001002029.3) 31.14%; CARMIL2 (NM_001013838.1) 0.0%; CD70 (NM_001252.4) 0.0%; CDCA7 (NM_031942.4) 0.0%; COPA (NM_004371.3) 0.0%; DNAJC21 (NM_001012339.2) 0.0%; DOCK2 (NM_004946.2) 0.0%; GINS1 (NM_021067.4) 0.0%; HELLS (NM_018063.4) 0.0%; IKBKG (NM_001099857.2) 29.03%; IL17RC (NM_153461.3) 0.0%; LAT (NM_001014987.1) 0.0%; MSN (NM_002444.2) 0.0%; MYSM1 (NM_001085487.2) 0.0%; NCF1 (NM_000265.5) 69.21%; OTULIN (NM_138348.5) 0.0%; RIPK1 (NM_003804.4) 0.0%; SGPL1 (NM_003901.3) 0.0%; SPPL2A (NM_032802.3) 0.0%.```
