### ISSUE TITLE
Fun characters in panel names

### ISSUE THREAD

**Issue by mattgarner** [eastgenomics/athena#30]
`R78.1_Hereditary neuropathy or pain disorder – NOT PMP22 copy number_P`

![image](https://user-images.githubusercontent.com/8166553/121211996-d9c10800-c874-11eb-999d-f7c5a9e76e9b.png)
`–` -> `â€“`

Test directory uses a mix of long and short dashes in different CIs because test directory

**Comment by jethror1** [comment]
Well that's fun 🙂 

I'm surprised as it should encode with UTF8 fine, probably can just add a replace with a short dash if not else

**Comment by jethror1** [comment]
Actually this is parsed from the bed file filename. @mattgarner is the output of generate bed correct or also wrongly encoded?

**Comment by jethror1** [comment]
found the issue, it's bootstrap being 'helpful', pasting it into an empty .html file is fine, adding bootstrap link breaks it.

Adding `charset="UTF-8"` to the meta tag in the head of the page fixes this, will require adding the the template file for next release
